// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbwcwjutcgojftypzxdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhid2N3anV0Y2dvamZ0eXB6eGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTkyNTEsImV4cCI6MjA2ODIzNTI1MX0.1isSvWuMIhQsroLhwBT1qkV_Hsv1XVu4KX7rVxeoYys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});